(()=>{'use strict';
const tg=window.Telegram?.WebApp||null,$=id=>document.getElementById(id);
const DS_KEY='lw_v544_state',CLOUD_CORE='lw_v544_core',CLOUD_EVENTS='lw_v544_events';
const uid=String(tg?.initDataUnsafe?.user?.id||'');
const LOCAL_KEY=uid?`lw_v544_local_${uid}`:'';
const THEMES={aura:['Aura','#ff4f9a','#8b5cf6'],noir:['Noir','#d7c4ff','#5f3fc4'],ice:['Ice','#52e7ff','#526dff'],ruby:['Ruby','#ff3b6b','#9c1fff'],gold:['Gold','#ffc67a','#d855ff'],emerald:['Emerald','#54ffc2','#0d8d8a']};
const MAP={love:'aura',ocean:'ice',sunset:'gold',midnight:'noir',berry:'ruby',rose:'ruby'};
let timer,L={themeId:'aura',events:[]};
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function toast(t){clearTimeout(timer);$('toast').textContent=t;$('toast').classList.add('show');timer=setTimeout(()=>$('toast').classList.remove('show'),1800)}
function parse(v){try{const x=JSON.parse(v);return x&&typeof x==='object'?x:null}catch{return null}}
function isHex(v){return /^#[0-9a-f]{6}$/i.test(String(v||''))}
function dateParts(v){const m=/^(\d{4})-(\d{2})-(\d{2})$/.exec(String(v||''));if(!m)return null;const y=+m[1],mo=+m[2],d=+m[3],x=new Date(y,mo-1,d,12);return x.getFullYear()===y&&x.getMonth()===mo-1&&x.getDate()===d?{y,m:mo-1,d}:null}
function localISO(d=new Date()){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function localDate(v){const p=dateParts(v);return p?new Date(p.y,p.m,p.d,12):null}
function fmt(v){const d=localDate(v);return d?d.toLocaleDateString('ru-RU',{day:'2-digit',month:'long',year:'numeric'}):'Дата не настроена'}
function days(v){const a=localDate(v);if(!a)return 0;const b=new Date();b.setHours(12,0,0,0);return b<a?0:Math.round((b-a)/86400000)+1}
function clampDate(y,m,d){return new Date(y,m,Math.min(d,new Date(y,m+1,0,12).getDate()),12)}
function dateToISO(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function breakdown(v){const s=localDate(v);if(!s)return[0,0,0];const e=new Date();e.setHours(12,0,0,0);if(e<s)return[0,0,0];let y=e.getFullYear()-s.getFullYear(),c=clampDate(s.getFullYear()+y,s.getMonth(),s.getDate());if(c>e){y--;c=clampDate(s.getFullYear()+y,s.getMonth(),s.getDate())}let m=0;while(m<11){const nm=c.getMonth()+1,ny=c.getFullYear()+Math.floor(nm/12),mm=nm%12,n=clampDate(ny,mm,s.getDate());if(n>e)break;c=n;m++}return[Math.max(0,y),m,Math.max(0,Math.round((e-c)/86400000))]}
function milestone(v){const s=localDate(v);if(!s)return null;const t=new Date();t.setHours(12,0,0,0);const el=days(v),next=(Math.floor(el/100)+1)*100,h=new Date(s);h.setDate(h.getDate()+next-1);let a=clampDate(t.getFullYear(),s.getMonth(),s.getDate());if(a<=t)a=clampDate(t.getFullYear()+1,s.getMonth(),s.getDate());const target=h<a?h:a;return{label:h<a?`${next} дней`:'годовщина',date:target,left:Math.max(0,Math.round((target-t)/86400000))}}
function sanitize(raw){const x=raw&&typeof raw==='object'?raw:{},o={themeId:'aura',events:[]};let th=MAP[x.themeId]||x.themeId||'aura';if(!THEMES[th])th='aura';o.themeId=th;if(typeof x.n1==='string')o.n1=x.n1.trim().slice(0,24);if(typeof x.n2==='string')o.n2=x.n2.trim().slice(0,24);if(dateParts(x.rel)&&String(x.rel)<=localISO())o.rel=String(x.rel);if(isHex(x.accent))o.accent=x.accent;for(const k of ['av1','av2'])if(typeof x[k]==='string'&&x[k].startsWith('data:image/')&&x[k].length<1900000)o[k]=x[k];if(Array.isArray(x.events))o.events=x.events.slice(0,40).map(e=>({title:String(e?.title||'').trim().slice(0,40),event_date:String(e?.event_date||'')})).filter(e=>e.title&&dateParts(e.event_date));return o}
function dsGet(){return new Promise(r=>{const d=tg?.DeviceStorage;if(!d?.getItem)return r(null);try{d.getItem(DS_KEY,(e,v)=>r(e?null:v||null))}catch{r(null)}})}
function dsSet(v){return new Promise(r=>{const d=tg?.DeviceStorage;if(!d?.setItem)return r(false);try{d.setItem(DS_KEY,v,(e,ok)=>r(!e&&ok!==false))}catch{r(false)}})}
function dsRemove(){return new Promise(r=>{const d=tg?.DeviceStorage;if(!d?.removeItem)return r(false);try{d.removeItem(DS_KEY,()=>r(true))}catch{r(false)}})}
function cloudGet(key){return new Promise(r=>{const c=tg?.CloudStorage;if(!c?.getItem)return r(null);try{c.getItem(key,(e,v)=>r(e?null:v||null))}catch{r(null)}})}
function cloudSet(key,v){return new Promise(r=>{const c=tg?.CloudStorage;if(!c?.setItem)return r(false);try{c.setItem(key,v,(e,ok)=>r(!e&&ok!==false))}catch{r(false)}})}
function cloudRemove(key){return new Promise(r=>{const c=tg?.CloudStorage;if(!c?.removeItem)return r(false);try{c.removeItem(key,()=>r(true))}catch{r(false)}})}
function readLocal(){if(!LOCAL_KEY)return null;try{return parse(localStorage.getItem(LOCAL_KEY))}catch{return null}}
function writeLocal(x){if(!LOCAL_KEY)return;try{localStorage.setItem(LOCAL_KEY,JSON.stringify(x))}catch{}}
async function loadState(){let x=parse(await dsGet());if(x)return sanitize(x);const core=parse(await cloudGet(CLOUD_CORE)),ev=parse(await cloudGet(CLOUD_EVENTS));if(core){core.events=Array.isArray(ev)?ev:[];x=sanitize(core);await dsSet(JSON.stringify(x));return x}x=readLocal();if(x){x=sanitize(x);await dsSet(JSON.stringify(x));return x}return{themeId:'aura',events:[]}}
async function saveState(){L=sanitize(L);const full=JSON.stringify(L);writeLocal(L);const ok=await dsSet(full);const core={...L};delete core.av1;delete core.av2;delete core.events;await cloudSet(CLOUD_CORE,JSON.stringify(core));await cloudSet(CLOUD_EVENTS,JSON.stringify(L.events||[]));return ok||!!tg?.CloudStorage||!!LOCAL_KEY}
async function resetState(){L={themeId:'aura',events:[]};if(LOCAL_KEY)try{localStorage.removeItem(LOCAL_KEY)}catch{};await Promise.all([dsRemove(),cloudRemove(CLOUD_CORE),cloudRemove(CLOUD_EVENTS)]);render();toast('Данные этого аккаунта сброшены')}
function theme(st={}){let id=MAP[st.themeId]||st.themeId||L.themeId||'aura';if(!THEMES[id])id='aura';const t=THEMES[id],a=isHex(st.accent)?st.accent:(isHex(L.accent)?L.accent:t[1]);document.documentElement.style.setProperty('--a',a);document.documentElement.style.setProperty('--b',t[2]);L.themeId=id;L.accent=a;$('accent').value=a;document.querySelectorAll('.theme').forEach(x=>x.classList.toggle('on',x.dataset.id===id))}
function avatar(el,d){el.style.backgroundImage=d?`url(${d})`:'';el.textContent=d?'':'♡'}
function renderEvents(){const a=L.events||[];$('empty').style.display=a.length?'none':'block';$('events').innerHTML=a.map((e,i)=>`<div class="event"><div class="eventIcon">✦</div><div><b>${esc(e.title)}</b><small>${esc(fmt(e.event_date))}</small></div><button class="del" data-i="${i}">×</button></div>`).join('');document.querySelectorAll('.del').forEach(x=>x.onclick=async()=>{L.events.splice(+x.dataset.i,1);await saveState();renderEvents();toast('Событие удалено')})}
function render(){const me=tg?.initDataUnsafe?.user?.first_name||L.n1||'Ты',n1=L.n1||me,n2=L.n2||'Половинка',rel=L.rel||'';$('p1').textContent=n1;$('p2').textContent=n2;$('names').textContent=n1+' × '+n2;$('date').textContent=fmt(rel);$('n1').value=n1;$('n2').value=n2;$('rel').value=rel;$('days').textContent=days(rel);const b=breakdown(rel);$('years').textContent=b[0];$('months').textContent=b[1];$('remain').textContent=b[2];const ms=milestone(rel);if(ms){$('mt').textContent=ms.label;$('mb').textContent=ms.left+' дн.';$('md').textContent=fmt(dateToISO(ms.date));$('prog').style.width=Math.max(5,100-Math.min(100,ms.left/3.65))+'%'}else{$('mt').textContent='Добавьте дату';$('mb').textContent='—';$('md').textContent='LW покажет ближайшую красивую отметку.';$('prog').style.width='0%'}avatar($('av1'),L.av1);avatar($('av2'),L.av2);theme();renderEvents()}
function open(t='profile'){$('sheet').classList.add('open');tab(t)}
function tab(t){document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('on',x.dataset.tab===t));document.querySelectorAll('.pane').forEach(x=>x.classList.toggle('on',x.id===(t==='events'?'eventsPane':t)))}
function imageData(file){return new Promise((res,rej)=>{const r=new FileReader();r.onerror=rej;r.onload=()=>{const i=new Image();i.onerror=rej;i.onload=()=>{const s=Math.min(1,900/Math.max(i.width,i.height)),c=document.createElement('canvas');c.width=Math.max(1,Math.round(i.width*s));c.height=Math.max(1,Math.round(i.height*s));c.getContext('2d').drawImage(i,0,0,c.width,c.height);let d=c.toDataURL('image/webp',.8);if(d.length>1500000)d=c.toDataURL('image/jpeg',.65);res(d)};i.src=String(r.result)};r.readAsDataURL(file)})}
async function pick(f,k){if(!f||!f.type.startsWith('image/'))return;if(f.size>8*1024*1024)return toast('Фото до 8 МБ');try{const d=await imageData(f);if(d.length>1800000)return toast('Фото слишком большое');L[k]=d;await saveState();render();toast('Фото сохранено')}catch{toast('Не удалось обработать фото')}}
function build(){ $('themes').innerHTML=Object.entries(THEMES).map(([id,t])=>`<button class="theme" data-id="${id}" style="background:linear-gradient(135deg,${t[1]},${t[2]})">${t[0]}</button>`).join('');document.querySelectorAll('.theme').forEach(x=>x.onclick=async()=>{L.themeId=x.dataset.id;theme();await saveState()})}
function bind(){document.querySelectorAll('.tab').forEach(x=>x.onclick=()=>tab(x.dataset.tab));document.querySelectorAll('[data-nav]').forEach(x=>x.onclick=()=>{document.querySelectorAll('[data-nav]').forEach(y=>y.classList.toggle('on',y===x));x.dataset.nav==='home'?scrollTo({top:0,behavior:'smooth'}):open(x.dataset.nav)});$('close').onclick=()=>$('sheet').classList.remove('open');$('sheet').onclick=e=>{if(e.target===$('sheet'))$('sheet').classList.remove('open')};$('quick').onclick=()=>open('events');$('av1').onclick=()=>$('av1f').click();$('av2').onclick=()=>$('av2f').click();$('av1f').onchange=e=>pick(e.target.files[0],'av1');$('av2f').onchange=e=>pick(e.target.files[0],'av2');$('saveP').onclick=async()=>{const rel=$('rel').value;if(rel&&(!dateParts(rel)||rel>localISO()))return toast('Проверь дату начала');L.n1=$('n1').value.trim().slice(0,24);L.n2=$('n2').value.trim().slice(0,24);if(rel)L.rel=rel;else delete L.rel;await saveState();render();toast('Сохранено')};$('addE').onclick=async()=>{const title=$('et').value.trim().slice(0,40),event_date=$('ed').value;if(!title||!dateParts(event_date))return toast('Заполни название и дату');if((L.events||[]).length>=40)return toast('Лимит 40 событий');L.events.push({title,event_date});await saveState();$('et').value='';renderEvents();toast('Событие добавлено')};$('accent').oninput=()=>theme({accent:$('accent').value});$('saveS').onclick=async()=>{L.accent=$('accent').value;await saveState();theme();toast('Стиль сохранён')};$('reset').onclick=resetState;$('export').onclick=()=>{const b=new Blob([JSON.stringify({version:'5.4.4',local:L},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='lw-backup-v544.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),800)};$('import').onclick=()=>$('imp').click();$('imp').onchange=async e=>{try{const f=e.target.files[0];if(!f||f.size>8*1024*1024)throw 0;const d=JSON.parse(await f.text());L=sanitize(d.local||d);await saveState();render();toast('Импортировано')}catch{toast('Некорректный JSON')}finally{e.target.value=''}};$('share').onclick=()=>{const d=days(L.rel||''),url=location.origin+'/lw-love-widget-miniapp/app-v544.html',text=L.rel?`💗 Сейчас идёт ${d}-й день нашей истории — LW`:'💗 LW — Love Widget';try{if(tg?.openTelegramLink)return tg.openTelegramLink('https://t.me/share/url?url='+encodeURIComponent(url)+'&text='+encodeURIComponent(text))}catch{}if(navigator.share)navigator.share({title:'LW — Love Widget',text,url}).catch(()=>{})}}
async function init(){try{tg?.ready();tg?.expand();tg?.disableVerticalSwipes?.();tg?.setHeaderColor?.('#07060d');tg?.setBackgroundColor?.('#07060d')}catch{}$('rel').max=localISO();build();bind();L=await loadState();render()}
init();
})();